version: "3.8"
# ici docker peux lancer plusieurs containers ( ou services )
# il y a que app commes service
# creation image plus rapide pour le dev
# command avant : npm run dev , maintenant : docker compose up
services:
  app:
    container_name: lt-coaching-app
    image: node:20-alpine

    working_dir: /app
  #code en live hot reload
    volumes:
      # synchronise ton code local
      - .:/app
      # évite conflits node_modules
      - /app/node_modules

    ports:
      - "3000:3000"
  # injecte les variables dans docker
    environment:
    # met en mode dev
      - NODE_ENV=development
      # prend les variable depuis .env
      - NEXT_PUBLIC_EMAILJS_SERVICE_ID=${NEXT_PUBLIC_EMAILJS_SERVICE_ID}
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}

    command: npm run dev